/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.project;

/**
 *
 * @author Nouelle
 */
public class FinalReceipt extends javax.swing.JPanel {

    /**
     * Creates new form FinalReceipt
     */
    public FinalReceipt(String n, double p, int q) {
        initComponents();
        Name.setText(n);
        price.setText(p + "");
        quantity.setText(q  + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        quantity = new javax.swing.JLabel();
        price = new javax.swing.JLabel();

        jLabel3.setText("Price");

        setMaximumSize(new java.awt.Dimension(400, 30));
        setMinimumSize(new java.awt.Dimension(400, 30));
        setPreferredSize(new java.awt.Dimension(400, 30));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setText("Order Name");
        Name.setMaximumSize(new java.awt.Dimension(220, 30));
        Name.setMinimumSize(new java.awt.Dimension(220, 30));
        Name.setPreferredSize(new java.awt.Dimension(220, 30));
        add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 40));

        quantity.setText("Price");
        quantity.setMaximumSize(new java.awt.Dimension(80, 30));
        quantity.setMinimumSize(new java.awt.Dimension(80, 30));
        quantity.setPreferredSize(new java.awt.Dimension(80, 30));
        add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 80, 40));

        price.setText("Price");
        price.setMaximumSize(new java.awt.Dimension(80, 30));
        price.setMinimumSize(new java.awt.Dimension(80, 30));
        price.setPreferredSize(new java.awt.Dimension(80, 30));
        add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 80, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel price;
    private javax.swing.JLabel quantity;
    // End of variables declaration//GEN-END:variables
}
