/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.project;

import javax.swing.JLabel;

/**
 *
 * @author reden
 */
public class Item_Category extends javax.swing.JPanel {

    private String categoryName;
    /**
     * Creates new form Item_Category
     */
    public Item_Category() {
        initComponents();
    }
    
    public Item_Category(String name) {
        initComponents();
        categoryName = name;
        this.setBackground(ColorTheme.accentColor);
        jl_category.setText("<html><div style='text-align: center;'>" + categoryName + "<div></html");
    }
    
    public String getCategoryName()
    {
        return categoryName;
    }

    public JLabel getJLabelName()
    {
        return jl_category;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_category = new javax.swing.JLabel();

        setBackground(new java.awt.Color(22, 36, 49));
        setMaximumSize(new java.awt.Dimension(215, 30));
        setMinimumSize(new java.awt.Dimension(215, 30));
        setPreferredSize(new java.awt.Dimension(215, 30));

        jl_category.setBackground(new java.awt.Color(255, 255, 255));
        jl_category.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_category.setForeground(new java.awt.Color(255, 255, 255));
        jl_category.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_category.setText("Category");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jl_category;
    // End of variables declaration//GEN-END:variables
}
