/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.project;

/**
 *
 * @author reden
 */
public class Item_Menu extends javax.swing.JPanel {

    private String menuName;
    private double menuPrice;
    /**
     * Creates new form Item_Category
     */
    public Item_Menu() {
        initComponents();
    }
    
    public Item_Menu(String name) {
        initComponents();
        jl_menu.setText("<html><div style='text-align: center;'>" + name + "<div></html");
    }

    public Item_Menu(String name, double price) {
        initComponents();
        menuName = name;
        menuPrice = price;
        jl_menu.setText("<html><div style='text-align: center;'>" + menuName + "<div></html");
    }
    
    public String getMenuName()
    {
        return menuName;
    }
    
    public double getMenuPrice()
    {
        return menuPrice;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_menu = new javax.swing.JLabel();

        setBackground(new java.awt.Color(22, 36, 49));
        setMaximumSize(new java.awt.Dimension(165, 180));
        setMinimumSize(new java.awt.Dimension(165, 180));
        setPreferredSize(new java.awt.Dimension(165, 180));

        jl_menu.setBackground(new java.awt.Color(255, 255, 255));
        jl_menu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_menu.setForeground(new java.awt.Color(255, 255, 255));
        jl_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_menu.setText("Menu");
        jl_menu.setPreferredSize(new java.awt.Dimension(165, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jl_menu;
    // End of variables declaration//GEN-END:variables
}
