/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.project;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author reden
 */
public class Item_AddCategory extends javax.swing.JPanel {

    private boolean isOpen = false;
    private ArrayList<Item_AddMenu> menuList = new ArrayList<>();;
    private String categoryName;
    /**
     * Creates new form Item_AddCategory
     */
    public Item_AddCategory() {
        initComponents();
        this.menuList = new ArrayList<>();
        jp_content.setVisible(false);
    }
    
    public Item_AddCategory(String name) {
        initComponents();
        categoryName = name;
        jl_categoryname.setText(name);
        jp_content.setVisible(false);
    }


    private void Open()
    {
        jp_content.setVisible(isOpen);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_categoryname = new javax.swing.JLabel();
        edit = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        jp_content = new javax.swing.JPanel();
        jp_addMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBackground(new java.awt.Color(58, 85, 111));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 50));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_categoryname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_categoryname.setForeground(new java.awt.Color(255, 255, 255));
        jl_categoryname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_categoryname.setText("Category Name");
        jl_categoryname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jl_categorynameMouseReleased(evt);
            }
        });
        jPanel1.add(jl_categoryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1080, 50));

        edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-white.png"))); // NOI18N
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 40, 50));

        delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete-white.png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteMouseReleased(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 40, 50));

        add(jPanel1);

        jp_content.setMaximumSize(new java.awt.Dimension(1200, 32767));
        jp_content.setMinimumSize(new java.awt.Dimension(0, 0));
        jp_content.setLayout(new javax.swing.BoxLayout(jp_content, javax.swing.BoxLayout.PAGE_AXIS));

        jp_addMenu.setBackground(new java.awt.Color(255, 255, 255));
        jp_addMenu.setMaximumSize(new java.awt.Dimension(1200, 40));
        jp_addMenu.setMinimumSize(new java.awt.Dimension(1200, 40));
        jp_addMenu.setPreferredSize(new java.awt.Dimension(1200, 40));
        jp_addMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jp_addMenuMouseReleased(evt);
            }
        });
        jp_addMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("+ Add Menu");
        jp_addMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 1, 665, 40));

        jp_content.add(jp_addMenu);

        add(jp_content);
    }// </editor-fold>//GEN-END:initComponents

    private void jp_addMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_addMenuMouseReleased
        // TODO add your handling code here:
       
        try {
             JOP_Menu tempMenu = new JOP_Menu();
            int value = JOptionPane.showConfirmDialog(SwingUtilities.getWindowAncestor(this),
                            tempMenu,
                            "Add Account",
                            JOptionPane.OK_CANCEL_OPTION,
                            JOptionPane.PLAIN_MESSAGE);

            if(value == JOptionPane.OK_OPTION && !tempMenu.menuName.getText().isEmpty() && !tempMenu.menuPrice.getText().isEmpty())
            {
                Item_AddMenu temp = new Item_AddMenu(this, tempMenu.menuName.getText(), Double.parseDouble(tempMenu.menuPrice.getText()));
                jp_content.add(temp, 0);
                menuList.add(temp);
                jp_content.repaint();
                jp_content.revalidate();
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jp_addMenuMouseReleased

    private void jl_categorynameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_categorynameMouseReleased
        // TODO add your handling code here:
        isOpen = !isOpen;
        Open();
    }//GEN-LAST:event_jl_categorynameMouseReleased

    private void deleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseReleased

    public void removeMenu(Item_AddMenu menu)
    {
        if(menuList.contains(menu))
        {
            menuList.remove(menu);
            jp_content.remove(menu);
            jp_content.repaint();
            jp_content.revalidate();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel delete;
    private javax.swing.JLabel edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl_categoryname;
    private javax.swing.JPanel jp_addMenu;
    private javax.swing.JPanel jp_content;
    // End of variables declaration//GEN-END:variables
}
