/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.project;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author reden
 */
public class Item_Receipt extends javax.swing.JPanel {

    
    private String m_name;
    private double m_price = 0.00;
    private int m_quantity = 1;
    private double m_currentPrice = 0.00;
    private JP_MenuCard m_parent = null;

    
    
    
    public String getM_name() {
        return m_name;
    }

    public int getM_quantity() {
        return m_quantity;
    }

    /**
     * Creates new form Item_Receipt
     */
    public double getM_currentPrice() {
        return m_currentPrice;
    }

    public Item_Receipt() {
        initComponents();
    }
    
    public Item_Receipt(JP_MenuCard parent, String name, double price) {
        initComponents();
        m_parent = parent;
        m_name = name;
        m_price = price;
        m_currentPrice = price;
        menuName.setText(name);
        menuPrice.setText((price * m_quantity) + "");
        menuQuantity.setText(m_quantity + "");
    }


    private void changeQuantity(int i)
    {
        m_quantity = Math.max(1, m_quantity + i);
        m_currentPrice = m_price * m_quantity;
        menuPrice.setText(m_currentPrice+ "");
        menuQuantity.setText(m_quantity + "");
        m_parent.recalculateTotal();
    }
    
    public String getMenuName()
    {
        return m_name;
    }
    
    public double getMenuPrice()
    {
        return m_price;
    }
    
    public double getCurrentPrice()
    {
        return m_currentPrice;
    }
    
    public int getMenuQuantity()
    {
        return m_quantity;
    }
    
    public void addQuantity()
    {
        changeQuantity(1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuName = new javax.swing.JLabel();
        menuQuantity = new javax.swing.JLabel();
        subtract = new javax.swing.JLabel();
        menuPrice = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        add = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(510, 30));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menuName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuName.setText("CHICKEN WINGS BREASST 1 PC");
        add(menuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 30));

        menuQuantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menuQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuQuantity.setText("1");
        add(menuQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 40, 30));

        subtract.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subtract-black.png"))); // NOI18N
        subtract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                subtractMouseReleased(evt);
            }
        });
        add(subtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 30, 30));

        menuPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menuPrice.setText("20.00");
        add(menuPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 70, 30));

        delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete-black.png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteMouseReleased(evt);
            }
        });
        add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 30, 30));

        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-black.png"))); // NOI18N
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addMouseReleased(evt);
            }
        });
        add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseReleased
        // TODO add your handling code here:
        changeQuantity(1);
    }//GEN-LAST:event_addMouseReleased

    private void subtractMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtractMouseReleased
        // TODO add your handling code here:
        changeQuantity(-1);
    }//GEN-LAST:event_subtractMouseReleased

    private void deleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseReleased
        // TODO add your handling code here:
  
        JOP_ConfirmDelete confirmDelete = new JOP_ConfirmDelete();
        int value = JOptionPane.showConfirmDialog(SwingUtilities.getWindowAncestor(this),
                        confirmDelete,
                        "Confirm Delete",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.PLAIN_MESSAGE);

        if(value == JOptionPane.OK_OPTION && !confirmDelete.username.getText().isEmpty() && !confirmDelete.password.getText().isEmpty())
        {
            String user = "";
            String pass ="";
            String type = "";
            Database.LoadAccount("Accounts");
            for (int i = 0; i < Database.loadAccounts.size(); i++) {
                if(Database.loadAccounts.get(i).getUsername().equals(confirmDelete.username.getText()))
                {
                    user = Database.loadAccounts.get(i).getUsername();
                    pass = Database.loadAccounts.get(i).getPassword();
                    type = Database.loadAccounts.get(i).getType();
                    break;
                }
            }
            if(confirmDelete.username.getText().equals(user) && confirmDelete.password.getText().equals(pass))
            {
                if(type.equals("Manager"))
                {
                    m_parent.removeReceipt(m_name);
                    System.out.println("DELETE");
                }
            }
        }
    }//GEN-LAST:event_deleteMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel menuName;
    private javax.swing.JLabel menuPrice;
    private javax.swing.JLabel menuQuantity;
    private javax.swing.JLabel subtract;
    // End of variables declaration//GEN-END:variables
}
