/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.project;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author reden
 */
public class JF_Main extends javax.swing.JFrame {

    
    private JPanel selectedButton = null;
    
    /**
     * Creates new form JF_Main
     */
    public JF_Main() {
        initComponents();
        selectedButton = jp_menu;
        jp_mainArea.add(new JP_Menu(),"menu");
    }

    private void selectButton(String s)
    {
        if(selectedButton != null) selectedButton.setBackground(ColorTheme.primaryColor);
        
        if(selectedButton == jp_menu) menuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu-white.png")));
        else if(selectedButton == jp_stocks) stocksIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checklist-white.png")));
        else if(selectedButton == jp_logs) logsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logs-white.png")));
        else if(selectedButton == jp_accounts) accountsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roundaccount-white.png")));
        
        switch(s)
        {
            case "menu":
                selectedButton = jp_menu;
                menuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu-black.png")));
                break;
            case "logs":
                selectedButton = jp_logs;
                logsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logs-black.png")));
                break;
            case "stocks":
                selectedButton = jp_stocks;
                stocksIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checklist-black.png")));
                break;
            case "accounts":
                selectedButton = jp_accounts;
                accountsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roundaccount-black.png")));
                break;
        }
        selectedButton.setBackground(ColorTheme.secondaryColor);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_taskbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jp_buttons = new javax.swing.JPanel();
        jp_menu = new javax.swing.JPanel();
        menuIcon = new javax.swing.JLabel();
        jp_logs = new javax.swing.JPanel();
        logsIcon = new javax.swing.JLabel();
        jp_stocks = new javax.swing.JPanel();
        stocksIcon = new javax.swing.JLabel();
        jp_accounts = new javax.swing.JPanel();
        accountsIcon = new javax.swing.JLabel();
        jp_mainArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_taskbar.setBackground(new java.awt.Color(22, 36, 49));
        jp_taskbar.setMaximumSize(new java.awt.Dimension(1200, 30));
        jp_taskbar.setMinimumSize(new java.awt.Dimension(1200, 30));
        jp_taskbar.setPreferredSize(new java.awt.Dimension(1200, 30));
        jp_taskbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SWITCH USER >");
        jp_taskbar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 120, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CURRENT USER: ADMIN");
        jp_taskbar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, 50));

        jp_buttons.setPreferredSize(new java.awt.Dimension(280, 50));
        jp_buttons.setLayout(new java.awt.GridLayout(1, 0));

        jp_menu.setBackground(new java.awt.Color(197, 214, 222));
        jp_menu.setPreferredSize(new java.awt.Dimension(70, 50));
        jp_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu-black.png"))); // NOI18N
        menuIcon.setMaximumSize(new java.awt.Dimension(70, 50));
        menuIcon.setMinimumSize(new java.awt.Dimension(70, 50));
        menuIcon.setPreferredSize(new java.awt.Dimension(70, 50));
        menuIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuIconMouseReleased(evt);
            }
        });
        jp_menu.add(menuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jp_buttons.add(jp_menu);

        jp_logs.setBackground(new java.awt.Color(22, 36, 49));
        jp_logs.setPreferredSize(new java.awt.Dimension(70, 50));
        jp_logs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logsIcon.setForeground(new java.awt.Color(255, 255, 255));
        logsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logs-white.png"))); // NOI18N
        logsIcon.setMaximumSize(new java.awt.Dimension(70, 50));
        logsIcon.setMinimumSize(new java.awt.Dimension(70, 50));
        logsIcon.setPreferredSize(new java.awt.Dimension(70, 50));
        logsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logsIconMouseReleased(evt);
            }
        });
        jp_logs.add(logsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jp_buttons.add(jp_logs);

        jp_stocks.setBackground(new java.awt.Color(22, 36, 49));
        jp_stocks.setPreferredSize(new java.awt.Dimension(70, 50));
        jp_stocks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stocksIcon.setForeground(new java.awt.Color(255, 255, 255));
        stocksIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stocksIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checklist-white.png"))); // NOI18N
        stocksIcon.setMaximumSize(new java.awt.Dimension(70, 50));
        stocksIcon.setMinimumSize(new java.awt.Dimension(70, 50));
        stocksIcon.setPreferredSize(new java.awt.Dimension(70, 50));
        stocksIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                stocksIconMouseReleased(evt);
            }
        });
        jp_stocks.add(stocksIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jp_buttons.add(jp_stocks);

        jp_accounts.setBackground(new java.awt.Color(22, 36, 49));
        jp_accounts.setPreferredSize(new java.awt.Dimension(70, 50));
        jp_accounts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accountsIcon.setForeground(new java.awt.Color(255, 255, 255));
        accountsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roundaccount-white.png"))); // NOI18N
        accountsIcon.setMaximumSize(new java.awt.Dimension(70, 50));
        accountsIcon.setMinimumSize(new java.awt.Dimension(70, 50));
        accountsIcon.setPreferredSize(new java.awt.Dimension(70, 50));
        accountsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                accountsIconMouseReleased(evt);
            }
        });
        jp_accounts.add(accountsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jp_buttons.add(jp_accounts);

        jp_taskbar.add(jp_buttons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 50));

        getContentPane().add(jp_taskbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jp_mainArea.setBackground(new java.awt.Color(197, 214, 222));
        jp_mainArea.setMaximumSize(new java.awt.Dimension(1200, 650));
        jp_mainArea.setMinimumSize(new java.awt.Dimension(1200, 650));
        jp_mainArea.setPreferredSize(new java.awt.Dimension(1200, 650));
        jp_mainArea.setLayout(new java.awt.CardLayout());
        getContentPane().add(jp_mainArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1200, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIconMouseReleased
        // TODO add your handling code here:
        selectButton("menu");
    }//GEN-LAST:event_menuIconMouseReleased

    private void logsIconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logsIconMouseReleased
        // TODO add your handling code here:
        selectButton("logs");
    }//GEN-LAST:event_logsIconMouseReleased

    private void stocksIconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stocksIconMouseReleased
        // TODO add your handling code here:
        selectButton("stocks");
    }//GEN-LAST:event_stocksIconMouseReleased

    private void accountsIconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsIconMouseReleased
        // TODO add your handling code here:
        selectButton("accounts");
    }//GEN-LAST:event_accountsIconMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountsIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jp_accounts;
    private javax.swing.JPanel jp_buttons;
    private javax.swing.JPanel jp_logs;
    private javax.swing.JPanel jp_mainArea;
    private javax.swing.JPanel jp_menu;
    private javax.swing.JPanel jp_stocks;
    private javax.swing.JPanel jp_taskbar;
    private javax.swing.JLabel logsIcon;
    private javax.swing.JLabel menuIcon;
    private javax.swing.JLabel stocksIcon;
    // End of variables declaration//GEN-END:variables
}
