/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.project;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
/**
 *
 * @author Nouelle
 */
public class JOP_Receipt extends javax.swing.JPanel {

    /**
     * Creates new form JOP_Receipt
     * @param user
     * @param receipt
     */
    public JOP_Receipt(String user, double t, double c, double tx , double payment, ArrayList<Item_Receipt> receipt) {
        initComponents();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
        Date date = new Date();  
        lblTime.setText(formatter.format(date));
        currentuser.setText(user);
        DecimalFormat df = new DecimalFormat("#,###,##0.00");
        total.setText("PHP " + df.format(t));
        change.setText("PHP " +df.format(c));
        paymenttxt.setText("PHP " + df.format(payment));
        taxtxt.setText("PHP " +df.format(tx));
        points.setText(df.format((t * 0.02)));
        lblOrderNumber.setText("000" + (int)(Math.random() * 100000 + 1) + "");
        for (int i = 0; i < receipt.size(); i++) {
            receiptContainer.add(new FinalReceipt(receipt.get(i).getMenuName(),receipt.get(i).getCurrentPrice() ,receipt.get(i).getMenuQuantity()));
        }
        receiptContainer.repaint();
        receiptContainer.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentuser = new javax.swing.JLabel();
        lblOrderNumber = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        Description1 = new javax.swing.JLabel();
        Description2 = new javax.swing.JLabel();
        receiptContainer = new javax.swing.JPanel();
        footer = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        points = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        paymenttxt = new javax.swing.JLabel();
        taxtxt = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        change = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 30700));
        setMinimumSize(new java.awt.Dimension(400, 700));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 230));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("                     Jollibee STI Malolos");
        jLabel5.setMaximumSize(new java.awt.Dimension(400, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(400, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(" ---------------------Customer Receipt------------------------");
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 30));

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTime.setText("Time dito");
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 300, 50));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDate.setText("Date:");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 50));

        jLabel2.setText("=======================================================");
        jLabel2.setMaximumSize(new java.awt.Dimension(400, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(400, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 400, 30));

        currentuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        currentuser.setText("yung may gamit ng system now.");
        jPanel1.add(currentuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 230, 40));

        lblOrderNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOrderNumber.setText("69");
        jPanel1.add(lblOrderNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 220, 40));

        jLabel6.setText("=======================================================");
        jLabel6.setMaximumSize(new java.awt.Dimension(400, 30));
        jLabel6.setMinimumSize(new java.awt.Dimension(400, 30));
        jLabel6.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 400, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Order#:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cashier:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, 40));

        Description.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Description.setText("Quantity");
        jPanel1.add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 80, 30));

        Description1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Description1.setText("Description");
        jPanel1.add(Description1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 220, 30));

        Description2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Description2.setText("Price");
        Description2.setMaximumSize(new java.awt.Dimension(80, 30));
        Description2.setMinimumSize(new java.awt.Dimension(80, 30));
        Description2.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel1.add(Description2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 80, 30));

        add(jPanel1);

        receiptContainer.setMaximumSize(new java.awt.Dimension(400, 30000));
        receiptContainer.setLayout(new javax.swing.BoxLayout(receiptContainer, javax.swing.BoxLayout.PAGE_AXIS));
        add(receiptContainer);

        footer.setMaximumSize(new java.awt.Dimension(400, 500));
        footer.setMinimumSize(new java.awt.Dimension(400, 500));
        footer.setPreferredSize(new java.awt.Dimension(400, 250));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Thank You For Coming!");
        jLabel9.setMaximumSize(new java.awt.Dimension(400, 30));
        jLabel9.setMinimumSize(new java.awt.Dimension(400, 30));
        jLabel9.setPreferredSize(new java.awt.Dimension(400, 30));
        footer.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jLabel3.setText("=======================================================");
        footer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 400, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Points Earned:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        footer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Total Due:");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        footer.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 30));

        points.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        points.setText("0.00");
        points.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        footer.add(points, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 270, 30));

        total.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        total.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        total.setText("0.00");
        total.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        footer.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 240, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Payment:");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        footer.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, 30));

        paymenttxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paymenttxt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        paymenttxt.setText("0.00");
        paymenttxt.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        footer.add(paymenttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 230, 30));

        taxtxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taxtxt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        taxtxt.setText("0.00");
        taxtxt.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        footer.add(taxtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 240, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("VAT (12%):");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        footer.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Change:");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        footer.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 30));

        change.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        change.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        change.setText("0.00");
        change.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        footer.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 240, 30));

        add(footer);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Description1;
    private javax.swing.JLabel Description2;
    private javax.swing.JLabel change;
    public javax.swing.JLabel currentuser;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblDate;
    public javax.swing.JLabel lblOrderNumber;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel paymenttxt;
    private javax.swing.JLabel points;
    private javax.swing.JPanel receiptContainer;
    private javax.swing.JLabel taxtxt;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
