/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.project;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Nouelle
 */
public class JP_Accounts extends javax.swing.JPanel {

    private ArrayList<Item_Account> accounts = new ArrayList<>();

    public ArrayList<Item_Account> getAccounts() {
        return accounts;
    }

    public JPanel getC_content() {
        return c_content;
    }
    
    /**
     * Creates new form JP_Accounts
     */
    public JP_Accounts() {
        initComponents();
        Database.accounts.clear();
        updatemenu_sp.getVerticalScrollBar().setPreferredSize(new Dimension(0,0));
        updatemenu_sp.getVerticalScrollBar().setUnitIncrement(36);
        updatemenu_sp.getViewport().setBorder(null);
        updatemenu_sp.setViewportBorder(null);
        updatemenu_sp.setBorder(null);
        jp_addaccount.setBackground(ColorTheme.primaryColor);
        this.setBackground(ColorTheme.secondaryColor);
        Database.LoadAccount("Accounts");
        for (int i = 0; i < Database.loadAccounts.size(); i++) {
            addAccount(Database.loadAccounts.get(i).getUsername(),Database.loadAccounts.get(i).getPassword(),Database.loadAccounts.get(i).getType());
        }
    }
    
    public void addAccount(String name, String pass, String type)
    {
        Item_Account ac = new Item_Account(this,name, pass, type);
        Database.accounts.add(new AccountInfo(name,pass,type));
        accounts.add(ac);
        c_content.add(ac);
        c_content.repaint();
        c_content.revalidate();
        Database.SaveAccount("Accounts");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updatemenu_sp = new javax.swing.JScrollPane();
        c_container = new javax.swing.JPanel();
        c_content = new javax.swing.JPanel();
        jp_addaccount = new javax.swing.JPanel();
        jl_addaccount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 650));
        setMinimumSize(new java.awt.Dimension(1200, 650));
        setPreferredSize(new java.awt.Dimension(1200, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updatemenu_sp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        updatemenu_sp.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        updatemenu_sp.setMaximumSize(new java.awt.Dimension(1200, 560));
        updatemenu_sp.setMinimumSize(new java.awt.Dimension(1200, 560));
        updatemenu_sp.setPreferredSize(new java.awt.Dimension(1200, 560));

        c_container.setMinimumSize(new java.awt.Dimension(1200, 560));
        c_container.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        c_content.setMaximumSize(new java.awt.Dimension(300000, 300000));
        c_content.setOpaque(false);
        c_content.setLayout(new javax.swing.BoxLayout(c_content, javax.swing.BoxLayout.PAGE_AXIS));
        c_container.add(c_content);

        updatemenu_sp.setViewportView(c_container);

        add(updatemenu_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 490));

        jp_addaccount.setBackground(new java.awt.Color(22, 36, 49));
        jp_addaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jp_addaccountMouseReleased(evt);
            }
        });

        jl_addaccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_addaccount.setForeground(new java.awt.Color(255, 255, 255));
        jl_addaccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_addaccount.setText("ADD ACCOUNT");

        javax.swing.GroupLayout jp_addaccountLayout = new javax.swing.GroupLayout(jp_addaccount);
        jp_addaccount.setLayout(jp_addaccountLayout);
        jp_addaccountLayout.setHorizontalGroup(
            jp_addaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_addaccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_addaccount, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp_addaccountLayout.setVerticalGroup(
            jp_addaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_addaccount, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jp_addaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 190, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 270, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Accounts");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Username");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 220, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jp_addaccountMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_addaccountMouseReleased
        // TODO add your handling code here:
        JOP_Account tempAccount = new JOP_Account();
        int value = JOptionPane.showConfirmDialog(SwingUtilities.getWindowAncestor(this),
            tempAccount,
            "Add Account",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE);

        if(value == JOptionPane.OK_OPTION && !tempAccount.username.getText().isEmpty() && !tempAccount.password.getText().isEmpty())
        {
            addAccount(tempAccount.username.getText(), tempAccount.password.getText(), tempAccount.type.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jp_addaccountMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel c_container;
    private javax.swing.JPanel c_content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jl_addaccount;
    private javax.swing.JPanel jp_addaccount;
    private javax.swing.JScrollPane updatemenu_sp;
    // End of variables declaration//GEN-END:variables
}
