/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.project;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author reden
 */
public class JP_Menu extends javax.swing.JPanel implements MouseListener{

    private Item_Category selectedCategory = null;
    /**
     * Creates new form JP_Menu
     */
    public JP_Menu() {
        initComponents();
        this.setBackground(ColorTheme.secondaryColor);
        receipt_area.setBackground(ColorTheme.secondaryColor);
        menu_area.setBackground(ColorTheme.secondaryColor);
        this.setBackground(ColorTheme.secondaryColor);

        
        receipt_sp.getVerticalScrollBar().setPreferredSize(new Dimension(0,0));
        receipt_sp.getVerticalScrollBar().setUnitIncrement(36);
        receipt_sp.getViewport().setBorder(null);
        receipt_sp.setViewportBorder(null);
        receipt_sp.setBorder(null);
        
                                
        //setting category scroll pane
        category_sp.getHorizontalScrollBar().setPreferredSize(new Dimension(0,0));
        category_sp.getHorizontalScrollBar().setUnitIncrement(36);
        category_sp.getViewport().setBorder(null);
        category_sp.setViewportBorder(null);
        category_sp.setBorder(null);
        
        
        for (int i = 0; i < 30; i++) {
            System.out.println(i);
            String name = "Category " + (i+1); 
            Item_Category temp = new Item_Category(name);
            temp.addMouseListener(this);
            c_content.add(temp);
            menu_area.add(new JP_MenuCard(this, name), name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receipt_area = new javax.swing.JPanel();
        receipt_sp = new javax.swing.JScrollPane();
        r_container = new javax.swing.JPanel();
        r_content = new javax.swing.JPanel();
        item_Receipt1 = new com.project.project.Item_Receipt();
        item_Receipt2 = new com.project.project.Item_Receipt();
        item_Receipt3 = new com.project.project.Item_Receipt();
        item_Receipt4 = new com.project.project.Item_Receipt();
        item_Receipt5 = new com.project.project.Item_Receipt();
        item_Receipt6 = new com.project.project.Item_Receipt();
        item_Receipt7 = new com.project.project.Item_Receipt();
        item_Receipt8 = new com.project.project.Item_Receipt();
        item_Receipt9 = new com.project.project.Item_Receipt();
        item_Receipt10 = new com.project.project.Item_Receipt();
        item_Receipt11 = new com.project.project.Item_Receipt();
        item_Receipt12 = new com.project.project.Item_Receipt();
        item_Receipt13 = new com.project.project.Item_Receipt();
        item_Receipt14 = new com.project.project.Item_Receipt();
        item_Receipt15 = new com.project.project.Item_Receipt();
        item_Receipt16 = new com.project.project.Item_Receipt();
        item_Receipt17 = new com.project.project.Item_Receipt();
        item_Receipt18 = new com.project.project.Item_Receipt();
        item_Receipt19 = new com.project.project.Item_Receipt();
        item_Receipt20 = new com.project.project.Item_Receipt();
        item_Receipt21 = new com.project.project.Item_Receipt();
        item_Receipt22 = new com.project.project.Item_Receipt();
        menu_area = new javax.swing.JPanel();
        category_sp = new javax.swing.JScrollPane();
        c_container = new javax.swing.JPanel();
        c_content = new javax.swing.JPanel();

        setBackground(new java.awt.Color(197, 214, 222));
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receipt_area.setBackground(new java.awt.Color(204, 204, 204));
        receipt_area.setMaximumSize(new java.awt.Dimension(510, 650));
        receipt_area.setMinimumSize(new java.awt.Dimension(510, 650));
        receipt_area.setPreferredSize(new java.awt.Dimension(510, 650));
        receipt_area.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receipt_sp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        receipt_sp.setToolTipText("");
        receipt_sp.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        receipt_sp.setMaximumSize(new java.awt.Dimension(510, 400));
        receipt_sp.setMinimumSize(new java.awt.Dimension(510, 400));
        receipt_sp.setPreferredSize(new java.awt.Dimension(510, 400));
        receipt_sp.setViewportView(c_content);

        r_container.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        r_content.setOpaque(false);
        r_content.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        r_content.add(item_Receipt1);
        r_content.add(item_Receipt2);
        r_content.add(item_Receipt3);
        r_content.add(item_Receipt4);
        r_content.add(item_Receipt5);
        r_content.add(item_Receipt6);
        r_content.add(item_Receipt7);
        r_content.add(item_Receipt8);
        r_content.add(item_Receipt9);
        r_content.add(item_Receipt10);
        r_content.add(item_Receipt11);
        r_content.add(item_Receipt12);
        r_content.add(item_Receipt13);
        r_content.add(item_Receipt14);
        r_content.add(item_Receipt15);
        r_content.add(item_Receipt16);
        r_content.add(item_Receipt17);
        r_content.add(item_Receipt18);
        r_content.add(item_Receipt19);
        r_content.add(item_Receipt20);
        r_content.add(item_Receipt21);
        r_content.add(item_Receipt22);

        r_container.add(r_content);

        receipt_sp.setViewportView(r_container);

        receipt_area.add(receipt_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        add(receipt_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 510, 650));

        menu_area.setBackground(new java.awt.Color(197, 214, 222));
        menu_area.setPreferredSize(new java.awt.Dimension(700, 580));
        menu_area.setLayout(new java.awt.CardLayout());
        add(menu_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 660, 580));

        category_sp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        category_sp.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        category_sp.setPreferredSize(new java.awt.Dimension(660, 30));
        category_sp.setViewportView(c_content);

        c_container.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        c_content.setOpaque(false);
        c_content.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        c_container.add(c_content);

        category_sp.setViewportView(c_container);

        add(category_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel c_container;
    private javax.swing.JPanel c_content;
    private javax.swing.JScrollPane category_sp;
    private com.project.project.Item_Receipt item_Receipt1;
    private com.project.project.Item_Receipt item_Receipt10;
    private com.project.project.Item_Receipt item_Receipt11;
    private com.project.project.Item_Receipt item_Receipt12;
    private com.project.project.Item_Receipt item_Receipt13;
    private com.project.project.Item_Receipt item_Receipt14;
    private com.project.project.Item_Receipt item_Receipt15;
    private com.project.project.Item_Receipt item_Receipt16;
    private com.project.project.Item_Receipt item_Receipt17;
    private com.project.project.Item_Receipt item_Receipt18;
    private com.project.project.Item_Receipt item_Receipt19;
    private com.project.project.Item_Receipt item_Receipt2;
    private com.project.project.Item_Receipt item_Receipt20;
    private com.project.project.Item_Receipt item_Receipt21;
    private com.project.project.Item_Receipt item_Receipt22;
    private com.project.project.Item_Receipt item_Receipt3;
    private com.project.project.Item_Receipt item_Receipt4;
    private com.project.project.Item_Receipt item_Receipt5;
    private com.project.project.Item_Receipt item_Receipt6;
    private com.project.project.Item_Receipt item_Receipt7;
    private com.project.project.Item_Receipt item_Receipt8;
    private com.project.project.Item_Receipt item_Receipt9;
    private javax.swing.JPanel menu_area;
    private javax.swing.JPanel r_container;
    private javax.swing.JPanel r_content;
    private javax.swing.JPanel receipt_area;
    private javax.swing.JScrollPane receipt_sp;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        if(e.getComponent() instanceof Item_Category)
        {
            Item_Category t = (Item_Category) e.getComponent();
            if(selectedCategory != null)
            {
                selectedCategory.setBackground(ColorTheme.primaryColor);
                selectedCategory.getJLabelName().setForeground(ColorTheme.secondaryColor);
            }
            
            selectedCategory = t;
            selectedCategory.setBackground(ColorTheme.secondaryColor);
                selectedCategory.getJLabelName().setForeground(ColorTheme.primaryColor);
            CardLayout c = (CardLayout)menu_area.getLayout();
            c.show(menu_area, t.getCategoryName());
        }
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
